name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build application
      run: bun run export
      
    - name: Add .nojekyll file
      run: touch ./out/.nojekyll
      
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Deploy to GitHub Pages
      run: |
        # Create and switch to a new temporary branch
        git checkout --orphan gh-pages-temp
        
        # Remove all files from git tracking
        git rm -rf --cached .
        
        # Clean the working directory
        rm -rf * .github .husky .gitignore
        
        # Copy the built files from out directory
        cp -r out/* .
        
        # Create .nojekyll file to prevent Jekyll processing
        touch .nojekyll
        
        # Stage all files
        git add .
        
        # Commit changes
        git commit -m "Deploy to GitHub Pages"
        
        # Force push to gh-pages branch
        git push -f origin gh-pages-temp:gh-pages
        
        # Clean up: switch back to main branch
        git checkout main
